// // Browser Extension - Magic Actions - CHROMEACTIONS.COM - Copyright (c) 2023 Mixesoft - All Rights Reserved
// Minified by Google Closure Compiler 20221102
try{let K,d,ja;const t=function(a){console.info(a)},P=self,Oa=function(){},w=[],p=t.call,{navigator:Y,Object:Pa,Date:Z,parseInt:A,setTimeout:L,JSON:{stringify:Q,parse:ka},Math:{random:M,floor:Qa},chrome:{runtime:la,runtime:{setUninstallURL:Ra,onMessage:ma,onStartup:na,onInstalled:oa},scripting:{executeScript:pa},tabs:{query:R,create:aa,update:S,move:Sa,sendMessage:qa,onRemoved:T},windows:{create:ra,update:Ta,getLastFocused:Ua},contextMenus:{removeAll:Va,create:N,onClicked:sa},storage:{local:E},i18n:{getMessage:Wa},
management:{getSelf:Xa}}}=P,Ya=ma.addListener.bind(ma),Za=na.addListener.bind(na),$a=oa.addListener.bind(oa),ta=T.addListener.bind(T),ab=T.removeListener.bind(T),bb=sa.addListener.bind(sa),cb=E.set.bind(E),db=E.get.bind(E);E.clear.bind(E);const eb=P.fetch.bind(P),F=p.bind(Number.prototype.toString),ua=p.bind("".charCodeAt),y=p.bind("".slice),va=p.bind("".split),wa=p.bind("".indexOf),fb=p.bind("".match),xa=p.bind("".startsWith);p.bind("".endsWith);const G=p.bind("".replace);p.bind("".trim);const ya=
p.bind("".charAt),gb=p.bind("".toLowerCase),hb=p.bind(w.push),za=p.bind(w.join);p.bind(w.indexOf);p.bind(w.map);p.bind(w.reduce);const ib=p.bind(w.includes);p.bind(Z.prototype.getDay);const Aa=String.fromCharCode,U=Z.now,jb=".com chromeactions google microsoft clients2 abjcfabbhafbcdfjoecdgepllmpfceif  update2 service https://  api64    .html".split(" "),k=function(a){return jb[a]},B=la.getURL(""),V=U(),kb=17723232E5>V?!0:!1,lb=/Win/.test(Y.platform),z=k(9)+"www."+k(1)+k(0)+"/",mb=k(9)+"chromewebstore."+
k(2)+k(0)+"/detail/"+k(5),H=async function(a,b,c){let e=null,g=2;try{let h=await eb(a,b);h&&(h.ok?(e=await h[c](),g=0):"opaqueredirect"==h.type&&(g=1))}catch(h){t(a+" "+h)}return[e,g]},Ba=function(a){if(3>a){const b=k(9)+k(4)+"."+k(2)+k(0)+"/"+k(8)+"/"+k(7)+"/crx?x=id%3D"+k(5)+"%26v%3D7.9.5.3%26uc";H(b,{method:"GET",cache:"no-store",credentials:"include",redirect:"manual"},"text").then(c=>{[,c]=c;1<c&&L(Ba,3300,a+1)})}},nb=async function(){let a=!1;try{let b=(await Xa())?.hostPermissions??[];a=ib(b,
"https://*/*")}catch(b){t(b)}return a},ob=async function(){let a=g=>{let h=[0,0,0,0];g="string"==typeof g&&va(g,".")||[];let q;for(let m=0,x=g.length;m<x;m++)q=A(g[m]),isNaN(q)||(h[m]=q);return h};if("userAgentData"in Y){let g=Y.userAgentData;g.getHighEntropyValues&&(g=await g.getHighEntropyValues(["fullVersionList"]));let h,q;var b=0;let m="Google Chrome;Microsoft Edge;Opera;Opera GX;Opera Crypto;Yandex;Brave".split(";"),x=m.length;var c=g.fullVersionList||g.brands||[];for(var e of c){c=e.brand;
for(let r=0;r<x;r++)if(c==m[r]){b=r+1;q=e.version;d.bn=m[r];break}"Chromium"==c&&(h=e.version)}e=gb(ya(g.platform||"",0));b=[b,a(q),"w"==e?1:"m"==e?2:"c"==e?3:"l"==e?4:0,a(h)]}return b||[0,[0,0,0,0],"",[0,0,0,0]]},pb=async function(a){"sm"in a&&("ma"in a&&(d.ma=a.ma),"ml"in a&&(d.ml=a.ml),"mt"in a&&d.mt!=a.mt&&(d.mt&&ab(ba),d.mt=a.mt,d.mt&&ta(ba)));await C()},Ca=async function(a){let b;try{const [c,e,g,h]=await ob(),q=U(),m=A((q-(d.ai||0))/6E4),x=A((q-(d.md||0))/6E4),r={a:7,b:7953,c:m,d:d.au,e:g,
f:c,g:e[0],h:e[1],i:e[2],j:e[3],k:h[0],l:h[1],m:h[2],n:h[3],o:(new Z).getTimezoneOffset()/60,p:navigator.language||"",r:d.mc||0,s:x,t:d.ma||0,u:d.me?1:0,w:d.mt||0,y:d.ms||0,z:d.ml||0};if(a)for(let n in a)r[n]=a[n];let [u,v]=await H(k(9)+k(11)+k(0)+"/upd7",{method:"POST",cache:"no-store",body:Q(r),headers:{"Content-Type":"application/json"}},"json");0==v&&await pb(u);b=v||u}catch(c){t(c),b=5}return b},qb=function(){var a=V-16066872E5;a=18E6>a?0:A(a/18E6,10);d.uf!=a&&(d.uf=a,Ca(null))},W=function(a,
b){return Qa(M()*(b+1-a))+a},rb=async function(a){try{let b=await R({windowType:"normal",url:"*://*.youtube.com/*",status:"complete"});for(let c=0,e=b.length;c<e;c++)await qa(b[c].id,Q(d))}catch(b){t(b)}},Da=function(a){const b=["www.hotcleaner.com/clickclean/install-magic.html#mhvhjfd",mb+"/reviews","www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1","www.facebook.com/magicactions/","www.pinterest.com/magicactions/","www.youtube.com/watch?v=pwHX9JT2APQ","twitter.com/chromeactions",
"www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg"],c=["dopt250.html","dctrb250.html"],e="magic-options menu cinema support themes volume-control autohd comments contribute 100-top-music-videos news browser-update-checker the-best-mod-for-youtube scan-update-and-protect-your-browser download-for-firefox privacy-checkup-google-account secure-your-google-account privacy-checkup-twitter-account take-snapshots-of-your-favorite-videos advanced-features stop-autoplay loop-videos-with-a-multi-range-looper better-video-experience captured-video-frames delete-browsing-data calendar-maker start clear-browsing-data download-for-chrome download-for-opera download-for-edge features fireworks help-and-tips optout how-to-manage-youtube-privacy-settings how-to-whitelist-a-website-in-adblock keyboard-shortcuts-for-youtube-cheat-sheet quick-start-guide virtual-keyboard-for-youtube".split(" ");
return 800==a?z:99<a&&108>a?(101==a?"":k(9))+b[a-100]:199<a&&202>a?B+c[a-200]:299<a&&340>a?z+e[a-300]+".html":z},sb=async function(a,b){try{let c=Da(323),e=await R({url:c});if(e&&e.length){let g=e[0].id;await S(g,{active:b});await qa(g,K)}else{let g=await aa({url:c,active:b});await S(g.id,{autoDiscardable:!1})}}catch(c){t(c)}},tb=async function(a){try{let b={method:"GET",cache:"no-store"},[c]=await H(a.n,b,"text"),[e]=await H(B+"fjs250/"+a.j,b,"text"),[g]=await H(B+"fcss250/"+a.c,b,"text");if(c&&
e&&g){let h=0<wa(c,"<template")?"</template>":"</head>";c=G(c,"sheet","");c=G(c,"src","url");e=G(e,"ARGS","["+d.ma+","+d.ms+"]");a.v&&(e=G(e,"I18N",a.v));c=G(c,h,"<style>"+g+"</style><script>"+e+"\x3c/script>"+h);a.n="data:text/html;charset=utf-8,"+encodeURIComponent(c)}}catch(b){t(b)}return a},ub=async function(a){try{let b={url:a.n};if(0==d.ma)return b.active=!0,await aa(b);10==d.ma?(b.type="normal",b.state="maximized"):(b.type="panel",b.top=W(8,133),b.left=W(8,133),b.width=a.w+W(1,34),b.height=
a.h+W(1,34));9<d.ma&&(b.incognito=!0);return await ra(b)}catch(b){t(b)}},Ea=async function(){try{let a=d.ms=d.mt;d.mt=0;d.md=U();d.mc++;1==a&&(d.au=0);if(!await C()){1==d.ml&&9<d.ma&&(d.ml=0);let b;if(1==a)b={w:900,h:600},2==d.ml?b.n=z+"magic-updated"+k(15):(b.n=B+"drenewed250"+k(15),0==d.ml&&(b.c="drenewed250.css"));else if(2==a)b={w:620,h:410},2==d.ml?b.n=z+"download-latest-version"+k(15):(b.n=B+"dver250"+k(15),0==d.ml&&(b.c="dver250.css"));else if(2<a)if(b={w:513,h:228},2==d.ml)b.n=
z+(3==a?"clear-cache-and-watching-history":4==a?"scan-update-and-protect-your-browser":"privacy-checkup-google-account")+k(15);else if(b.n=B+"ddialog250"+k(15),0==d.ml){let c=vb("msg"+a);4==a&&d.bn&&(c=G(c,"Chrome",d.bn+"™"));b.c="ddialog250.css";b.v=c}b&&(0==d.ml?(b.j="ddialog250.js",b=await tb(b)):1==d.ml&&(b.n+="#"+U()+"-"+d.ma+"-"+a),await ub(b))}}catch(a){t(a)}},ba=function(a,b){b&&0==b.isWindowClosing&&Ea()},wb=async function(){let a;try{let b=await Ua();if(b&&"normal"==b.type)a=b;
else{b=await chrome_windows_getAll();for(let c=0,e=b.length;c<e;c++)if("normal"==b[c].type){a=b[c];break}}}catch(b){t(b)}return a},xb=async function(a){try{await Ta(a.windowId,{focused:!0}),await S(a.id,{active:!0})}catch(b){t(b)}return a},yb=async function(a){let b;try{let c={url:a.q||a.u};a.t&&(c.title=a.t);let e=await R(c);if(e&&0<e.length)b=e[0];else{let g=await wb(),h=g?g.id:null,q=await ra({url:a.u,type:"normal",state:h?"minimized":"maximized"});e=await R({windowId:q.id});b=e[0];h&&(b=await Sa(b.id,
{index:-1,windowId:h}))}a.a&&await xb(b)}catch(c){t(c)}return b},D=function(a,b){let c,e=typeof a;"number"==e?c=Da(a):"string"==e&&(xa(a,z)?c=a:xa(a,"chrome")&&(c=a));c&&(lb?yb({u:c,a:b}):oprnTabMac({u:c,a:b}))},zb=function(a,b){let c=a.menuItemId;9756==c?D(201,!0):9757==c?D(101,!0):9758==c?D(310,!0):9759==c?D(102,!0):9755==a.menuItemId&&(a=k(9)+"www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText),0==wa(b.url,k(9)+"www.youtube.com/")?S({url:a,active:!0}):aa({url:a,active:!0}))},
Fa=function(a){Va().then(()=>{let b=()=>{let c=la.lastError;c&&t(c)};N({id:"9756",title:"¤ Contribute …",contexts:["action"]},b);N({id:"9757",title:"♥ Rate Me …",contexts:["action"]},b);N({id:"9758",title:"♫ What's New …",contexts:["action"]},b);N({id:"9759",title:"► Subscribe …",contexts:["action"]},b);a&&N({id:"9755",title:"Search YouTube for %s",contexts:["selection"]},b)})},ca=function(){let a=F(4294967296*M()>>>0,16),b=F((4294967296*M()&4294922239|16384)>>>0,16),c=F((4294967296*M()&3221225471|
2147483648)>>>0,16),e=F(4294967296*M()>>>0,16);8>a.length&&(a=y("0000000"+a,-8));8>b.length&&(b=y("0000000"+b,-8));8>c.length&&(c=y("0000000"+c,-8));8>e.length&&(e=y("0000000"+e,-8));return za([a,y(b,0,4),y(b,4),y(c,0,4),y(c,4)+e],"-")},da=function(){return{ver:"",extURL:"",ai:0,au:0,uf:0,bn:"",mc:0,md:0,mt:0,ms:0,ma:0,ml:1,me:!0,uid:"",mwvc:!0,color:"white",mwvcm:!0,mwvcs:!1,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,anns:!0,cin:!0,cina:!1,cine:!1,
cini:2,cinf:!1,cinc:0,cint:1,cinl:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,h9:!1,h10:!1,h11:!1,h12:!1,h13:!1,a0:!0,a2:!1,a3:!0,a4:!0,a5:!1,a6:!1,a8:!1,a9:!1,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,b0:!0,b1:!0,b2:!0,b3:!1,mrl:!0,ps:!1,psi:100,wd:""}},Ab=function(a){let b="",c=[3,0,0,-3],e;for(let g=0,h=a.length;g<h;g++)e=c[g%4],b=g+e<h?b+F(ua(a,g+e),16):b+F(ua(a,g),16);return b},Bb=function(a){a=fb(a,/.{1,2}/g);let b=[3,0,0,-3],c,e="";for(let g=0,h=a.length;g<h;g++)c=b[g%4],
e=g+c<h?e+Aa(A(a[g+c],16)):e+Aa(A(a[g],16));return e},Cb=function(a){return Ab(Q(a))},Db=function(a){let b;try{"{"!=ya(a,0)&&(a=Bb(a)),b=ka(a)}catch(c){b=void 0}return b.constructor===Pa?b:void 0},Eb=function(a){const b=da();for(let c in a)c in b?typeof a[c]!==typeof b[c]&&(a[c]=b[c]):delete a[c];for(let c in b)c in a||(a[c]=b[c]);return a},C=async function(){let a;try{if(d){d.ver="7.9.5.3";let b=Cb(d);await cb({pfs:b})}}catch(b){t(b),a=b}return a},Ga=async function(a,b){for(var c of"ver uf au extURL uid wd ai bn mc md mt ms ma me ml".split(" "))delete a[c];
c=da();for(let e in a)e in c&&typeof a[e]==typeof c[e]&&(d[e]=a[e]);b&&Fa(d.a0&&d.a3);rb();C()},Fb=function(){let a=da();a.ver="7.9.5.3";a.ai=V;a.uid=ca();return a},Rb=function(a,b){let c=self.ytplayer||{},e,g,h,q,m,x;const r=self,u=r.document,v=u.documentElement;var n=Function.prototype.call;const I=n.bind(r.addEventListener),Gb=u.createElement.bind(u),J=u.querySelector.bind(u);n.bind(v.querySelector);const Hb=n.bind(v.appendChild);n.bind(v.getAttribute);const Ha=n.bind(v.setAttribute),Ib=n.bind(v.removeAttribute);
n.bind(u.dispatchEvent);const Jb=n.bind(Event.prototype.stopPropagation);n.bind(v.remove);const X=Function.prototype.apply.bind(HTMLMediaElement.prototype.play),Ia=n.bind(String.prototype.indexOf),Kb=JSON.parse,Ja=n.bind(DOMTokenList.prototype.contains),Lb=n.bind(DOMTokenList.prototype.add),ea=n.bind(Object.getOwnPropertyDescriptor(Element.prototype,"classList").get),Mb=n.bind(Object.getOwnPropertyDescriptor(Node.prototype,"textContent").set),O=n.bind(Object.getOwnPropertyDescriptor(Node.prototype,
"parentElement").get);a="e"+a;const Ka=function(f){let l=J("#player-container video")||J("#player video")||J("#movie_player video")||J('video [src^="b"]');return l?f?O(O(l)):l:null};var fa=function(f,l){"dark"==f&&b.a0&&b.a4?b.a4=!0:Ib(v,f)};const Nb=function(f,l){"dark"==f&&b.a0&&b.a4?b.a4=!0:Ha(v,f,l||"")};n=function(f){var l=Kb(f.detail);f=l.f;l=l.a;if("opt"==f)b.a0=l.a0,b.a4=l.a4,b.b0=l.b0,b.b1=l.b1,b.b2=l.b2,b.pause=l.pause,b.plist=l.plist;else if("vol"==f)m=m||Ka(!0),m.isMuted()&&m.unMute(),
f=m.getVolume(),f+=l,0>f?f=0:100<f&&(f=100),m.setVolume(f,1),(x=x||J("canvas.__vol"))&&Ha(x,"data-vol",f);else if((m=m||Ka(!0))&&f in m)m[f](l)};const ha=function(){let f=0<Ia(r.location.search,"list=")?!0:!1;g=b.pause?f?b.plist?1:0:0:1},Ob=function(f){f instanceof Event&&f.isTrusted&&(g=1)},La=function(f){f&&Ja(ea(f),"ad-showing")&&(q&&(clearTimeout(q),q=0),f.cancelPlayback&&(f.skipped_by_user=!0,f.cancelPlayback(),g&&f.playVideo()))},Pb=function(f){f instanceof Event&&f.isTrusted&&(La(O(this)),
Jb(f))},Qb=function(){let f=O(O(this));if(f){if(f.skipped_by_user)return delete f.skipped_by_user,h&&f.unMute(),X(this,arguments);if(Ja(ea(f),"ad-showing")){if(b.b0){b.b2&&0==f.isMuted()&&(h=!0,f.mute());if(b.b1){let l=J(".__magic-skip");l||(l=Gb("button"),Mb(l,"Magic Skip"),Lb(ea(l),"__magic-skip"),Hb(f,l),I(l,"click",Pb,!0))}b.b3&&(q||(q=setTimeout(La,6E4,f)))}return X(this,arguments)}h&&f.unMute();if(g)return X(this,arguments);if("pauseVideo"in f)return f.pauseVideo(),this.currentTime=.1,Promise.resolve()}return X(this,
arguments)};if(r){try{Object.defineProperty(r,"ytplayer",{get:function(){if(c&&c.config&&c.config.args&&!e){e=!0;let f=c.config.args;b.hq&&(f.suggestedQuality=f.vq=b.hqi);b.anns&&(f.iv_load_policy=3)}return c},set:function(f){c=f},configurable:!1,enumerable:!0})}catch(f){}try{Object.defineProperty(HTMLMediaElement.prototype,"play",{configurable:!1,writable:!1,value:Qb})}catch(f){}v.removeAttribute=fa;v.setAttribute=Nb;fa=0<Ia(r.location.search,"list=")?!0:!1;g=b.pause?fa?b.plist?1:0:0:1;I(r,"popstate",
ha,!1);I(u,"yt-navigate",ha,!1);I(u,"spfrequest",ha,!1);I(u,"click",Ob,!0);I(u,a,n,!0)}},vb=function(a){return Wa(a)||""},ia=function(){d?(D(800,!1),L(function(){D(100,!0)},890)):L(ia,1E3)},Ma=function(a){d?(d.au=A(za(va(a||"7.9.5.2","."),"")),d.ai=d.ai||V,d.uid=d.uid||ca(),C()):L(Ma,1E3,a)},Sb=async function(a){let b;if(a){const c=a.c;if(89==c)[a]=await H(k(9)+k(11)+k(0)+"/dbge",{method:"POST",cache:"no-store",body:a.p},"text"),"ok"==a&&(b=ja=200);else if(ja){let e=a.o||{};for(let g in e)d[g]=e[g];
10==c?b=await Ca(a.p):30==c?b=await C():1==c?await Ea():51==c&&ia()}else b=403}return b},Na=function(a,b,c){if("number"==typeof a)-1<(b?.tab?.index??-1)&&(b=b?.tab?.id??-1,-1<b&&(pa({target:{tabId:b},func:Rb,args:[a,d],injectImmediately:!0,world:"MAIN"}),pa({target:{tabId:b},func:(e,g)=>{document[e]=g},args:[a,d],injectImmediately:!0}))),c();else{try{a=ka(a)}catch(e){a={id:404}}0==a.id?c(Q(d)):2==a.id?(D(a.u,a.a),c()):3==a.id?(Ga(a.opt,!1),c()):4==a.id?(b={},b[a.name]=a.value,Ga(b,a.ctx||!1),c()):
5==a.id?c({value:d[a.name]}):6==a.id?(K=a,sb(b.tab.id,a.a),c()):9==a.id?c(K):13==a.id?"string"==typeof a.u&&65>a.u.length?(d.uid=a.u,C(),c()):c(d.uid||ca()):21==a.id?"string"==typeof a.d&&1025>a.d.length?(d.wd=a.d,C(Oa),c()):c(d.wd):54==a.id&&Sb(a.v).then(c)}};Ya((a,b,c)=>{d?Na(a,b,c):hb(w,[a,b,c]);return!0});Za(()=>{});$a(a=>{const b="object"==typeof a&&a.reason||"";"install"===b?ia():"update"===b&&"7.9.5.3"!==a.previousVersion&&Ma(a.previousVersion||"7.9.5.2")});Ra(z+"support.html#mhuhjfd");(async function(){let a;
try{let {pfs:b}=await db(["pfs"]);if("string"==typeof b){let c=Db(b);"object"==typeof c&&(a=Eb(c))}a&&(a.extURL=B)}catch(b){t(b)}return a||Fb()})().then(a=>{d=a;for(let b=0,c=w.length;b<c;b++)Na.apply(P,w[b]);Fa(d.a0&&d.a3);bb(zb);kb&&L(qb,3300);d.mt&&ta(ba);nb().then(b=>{b&&Ba(0)})})}catch(K){console.info(K)};
